### ISSUE TITLE
Use of old twitch API

### ISSUE THREAD

**Issue by romain-neil** [alexcaussades/SimplissimeTwitch#1]
In the file https://github.com/alexcaussades/SimplissimeTwitch/blob/9261e9230e528317e045482c6b27543613469bca/src/apitwitch.php#L28 its seems to be using the old api and not the new one (helyx or something like that). Thanks

**Comment by alexcaussades** [comment]
Bonjour oui une nouvelle version et en cour de préparation avec **"New Twitch API"** #1
